# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Arty_A7/Stopwatch_Lite/Arty-Master.xdc

# IP: ip/clk_wiz/clk_wiz.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz}]

# XDC: ip/clk_wiz/clk_wiz_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz}] {/inst }]/inst ]]

# XDC: ip/clk_wiz/clk_wiz.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz || ORIG_REF_NAME==clk_wiz}] {/inst }]/inst ]]

# XDC: ip/clk_wiz/clk_wiz_ooc.xdc
