# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Arty_A7/Stopwatch_Lite/Stopwatch_Lite.cache/wt [current_project]
set_property parent.project_path C:/Arty_A7/Stopwatch_Lite/Stopwatch_Lite.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-35:part0:1.0 [current_project]
set_property ip_output_repo c:/Arty_A7/Stopwatch_Lite/Stopwatch_Lite.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Arty_A7/Stopwatch_Lite/Stopwatch_Lite.srcs/sources_1/new/clk_divider.v
  C:/Arty_A7/Stopwatch_Lite/Stopwatch_Lite.srcs/sources_1/new/BCD_Decoder.v
  C:/Arty_A7/Stopwatch_Lite/Stopwatch_Lite.srcs/sources_1/new/top.v
}
read_ip -quiet C:/Arty_A7/Stopwatch_Lite/Stopwatch_Lite.srcs/sources_1/ip/clk_wiz/clk_wiz.xci
set_property used_in_implementation false [get_files -all c:/Arty_A7/Stopwatch_Lite/Stopwatch_Lite.srcs/sources_1/ip/clk_wiz/clk_wiz_board.xdc]
set_property used_in_implementation false [get_files -all c:/Arty_A7/Stopwatch_Lite/Stopwatch_Lite.srcs/sources_1/ip/clk_wiz/clk_wiz.xdc]
set_property used_in_implementation false [get_files -all c:/Arty_A7/Stopwatch_Lite/Stopwatch_Lite.srcs/sources_1/ip/clk_wiz/clk_wiz_ooc.xdc]
set_property is_locked true [get_files C:/Arty_A7/Stopwatch_Lite/Stopwatch_Lite.srcs/sources_1/ip/clk_wiz/clk_wiz.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Arty_A7/Stopwatch_Lite/Arty-Master.xdc
set_property used_in_implementation false [get_files C:/Arty_A7/Stopwatch_Lite/Arty-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a35ticsg324-1L


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
